### ISSUE TITLE
Crash on yaw_controller.py

### ISSUE THREAD

**Issue by moisesejimenezg** [moisesejimenezg/capstone#1]
Traceback (most recent call last):
  File "/home/student/repos/capstone/ros/src/twist_controller/dbw_node.py", line 133, in <module>
    DBWNode()
  File "/home/student/repos/capstone/ros/src/twist_controller/dbw_node.py", line 86, in __init__
    self.loop()
  File "/home/student/repos/capstone/ros/src/twist_controller/dbw_node.py", line 97, in loop
    self.dbw_enabled,
  File "/home/student/repos/capstone/ros/src/twist_controller/twist_controller.py", line 80, in control
    linear_velocity, angular_velocity, current_velocity
  File "/home/student/repos/capstone/ros/src/twist_controller/yaw_controller.py", line 23, in get_steering
    if abs(linear_velocity) > 0.0
TypeError: unsupported operand type(s) for *: 'float' and 'Bool'

**Comment by moisesejimenezg** [comment]
This might be linked to original bug.
Traceback (most recent call last):                     
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 160, in <module>
    WaypointUpdater()                                  
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 50, in __init__       
    self.__step()                                       
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 56, in __step          
    self.__publish_waypoints()                                                                                 
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 114, in __publish_waypoints
    lane = self.__generate_lane(next_waypoint_index)                                                           
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 108, in __generate_lane
    lane.waypoints = self.__generate_decelerating_waypoints(next_waypoint_index)                                
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 93, in __generate_decelerating_waypoints
    distance = self.distance(reference_waypoints, i, stop_index)                                                
  File "/home/student/repos/capstone/ros/src/waypoint_updater/waypoint_updater.py", line 152, in distance       
    waypoints[wp1].pose.pose.position, waypoints[i].pose.pose.position                                          
IndexError: list index out of range
# Happens when we pass stop line

**Comment by moisesejimenezg** [comment]
Fixed
